# Generated by Django 4.2.17 on 2025-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Growth',
        ),
        migrations.DeleteModel(
            name='Strength',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
