# Generated by Django 4.2.17 on 2025-10-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_delete_growth_delete_strength_personalinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.CharField(blank=True, help_text='Path to logo image in static files', max_length=200),
        ),
    ]
